### ISSUE TITLE
.linguist.yml needs some refactoring

### ISSUE THREAD

**Issue by luizperes** [github-aux/linguist-unknown#16]
I believe we should do some refactoring for the `.linguist.yml` file.

We can keep the keyword `grammar` and organize it more or less like:
![linguist](https://user-images.githubusercontent.com/6173065/27893167-f9811ada-61b8-11e7-9099-5f1fa78531fb.png)

We could also implement something like operator overload with a keyword `pattern`, for exemple:

```
pattern:
  id: regex
  number: regex
```

**Comment by luizperes** [comment]
Decided lastly to keep the pattern in:

```YAML
C:
  extensions:
    - ".c"

  default:
    color: "#24292e"

  identifier:
    color: "#7b9c0e"

  number:
    color: "#745296"

  string:
    color: "#8B9EB7"

  comment:
    color: "#969896"
    single_line: "//"
    begin_multiline: "/*"
    end_multiline: "*/"

  group:
    - color: "#a71d5d"
      keywords:
        - "include"
        - "void"
        - "int"
        - "float"

    - color: "#FF1053"
      keywords:
        - "printf"
        - "putchar"
        - "getchar"
```
